{
 "title": "Log Visualization",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Error Rates",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate({job=\"generated-logs\", status_code=~\"4..|5..\"} | json [$__interval])) / sum(rate({job=\"generated-logs\"}[$__interval]))",
     "legendFormat": "Error Rates"
    }
   ]
  },
  {
   "title": "Average Response time (ms)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time({job=\"generated-logs\"} |json | unwrap response_time_ms [$__interval]))"
    }
   ]
  },
  {
   "title": "transaction volume",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"generated-logs\"} | json |= `transaction_id` [$__interval]))",
     "legendFormat": "transcation volume"
    }
   ]
  },
  {
   "title": "Error Rates by Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate({job=\"generated-logs\", status_code=~\"4..|5..\"} | json [$__interval])) / sum(rate({job=\"generated-logs\"}[$__interval]))",
     "legendFormat": "error rates"
    }
   ]
  },
  {
   "title": "Transaction Volume by Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"generated-logs\"} | json |= `transaction_id` [$__interval]))",
     "legendFormat": "Transaction Volume"
    }
   ]
  },
  {
   "title": "Average Response Time by Time Series",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time({job=\"generated-logs\"} |json | unwrap response_time_ms [$__interval]))",
     "legendFormat": "Response Time"
    }
   ]
  }
 ]
}