server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://loki-gateway:80/loki/api/v1/push
      tenant_id: docker

scrape_configs:
  - job_name: generated-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: generated-logs
          __path__: /var/log/generated.log
    pipeline_stages:
      - json:
          expressions:
            service_name: 'service_name'
            status_code: "status_code"
            user_id: "user_id"
            transaction_id: "transaction_id"
      - labels:
          service_name:
          status_code:
          user_id:
          transaction_id: